---
title: "R Notebook"
output: html_notebook
---

```{r}
library(infer)
```

# Age Hypothesis Test

```{r}
admission_sample <- admission_demographics_all %>%
    mutate(over_50 = case_when(
    age == "0-9" ~ "Under 50",
    age == "10-19" ~ "Under 50",
    age == "20-29" ~ "Under 50",
    age == "30-39" ~ "Under 50",
    age == "40-49" ~ "Under 50",
    age == "50-59" ~ "Over 50",
    age == "60-69" ~ "Over 50",
    age == "70-79" ~ "Over 50",
    age == "80-89" ~ "Over 50",
    age == "90 Plus" ~ "Over 50"
    )
  )
```

```{r}
observed_stat <- admission_sample %>% 
  specify(episodes ~ over_50) %>%
  calculate(stat = "diff in means", order = c("Over 50", "Under 50"))
```

```{r}
observed_stat
```

```{r}
null_distribution <- admission_sample %>% 
  specify(response = episodes, explanatory = over_50) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c("Over 50", "Under 50"))
```

```{r}
null_distribution %>%
  visualise() +
  shade_p_value(obs_stat = observed_stat, direction = "both")
```

```{r}
p_value_age <- null_distribution %>%
  get_p_value(obs_stat = observed_stat, direction = "both")
```

# Gender Hypothesis Test

```{r}

observed_stat_gender <- admission_sample %>% 
  specify(episodes ~ sex) %>%
  calculate(stat = "diff in means", order = c("Female", "Male"))

```

```{r}
null_distribution_gender <- admission_sample %>% 
  specify(response = episodes, explanatory = sex) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c("Female", "Male"))
```

```{r}
null_distribution_gender %>%
  visualise() +
  shade_p_value(obs_stat = observed_stat_gender, direction = "both")
```

```{r}
p_value_gender <- null_distribution_gender %>%
  get_p_value(obs_stat = observed_stat_gender, direction = "both")
```

# Deprivation Hypothesis Test

```{r}
admission_deprivation_filtered <- admission_deprivation_all %>% 
  filter(simd %in% c("1", "5"))
```

```{r}
observed_stat_deprivation <- admission_deprivation_filtered %>%
  mutate(simd = as.character(simd)) %>% 
  specify(episodes ~ simd) %>%
  calculate(stat = "diff in means", order = c("1", "5"))
```

```{r}
null_distribution_deprivation <- admission_deprivation_filtered %>% 
  mutate(simd = as.character(simd)) %>% 
  specify(response = episodes, explanatory = simd) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c("1", "5"))
```

```{r}
null_distribution_deprivation %>%
  visualise() +
  shade_p_value(obs_stat = observed_stat_deprivation, direction = "both")
```

```{r}
p_value_gender <- null_distribution_deprivation %>%
  get_p_value(obs_stat = observed_stat_deprivation, direction = "both")
```

