---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(leaflet)
library(DT)
library(Hmisc)
library(bslib)
library(shinyWidgets)
library(leafpop)

clean_hosp_admissions_qyear <- read_csv(here("app/clean_data/clean_hosp_admissions_qyear.csv"))

```

# Mean Average Length of Stay Q3 2017 to Q3 2022
```{r}
clean_hosp_admissions_qyear %>% 
  filter(!is.na(average_length_of_stay)) %>% 
  group_by(quarter) %>% 
summarise(mean(average_length_of_stay),
            sd(average_length_of_stay),
            sd(average_length_of_stay)/sqrt(length(average_length_of_stay)))


clean_hosp_admissions_qyear %>% 
  filter(nhs_health_board != "All of Scotland",
         admission_type %in% "All Inpatients") %>% 
  filter(nhs_health_board %in% "Lothian") %>% 
  ggplot() +
  aes(x = quarter, y = average_length_of_stay) + 
  stat_summary(fun.data = "mean_se",,
               geom = "errorbar",
               width = 0.5) +
  stat_summary(fun = "mean", geom = "point", size = 4, shape = 17) +
  stat_summary(fun = "mean",
               geom = "line",
               color = "black",
               group = 1) +
  theme_bw() +
  labs(
    x = "Quarter",
    y = "Average Length of Stay",
    title = "Mean Average Length of Stay Q3 2017 to Q3 2022") +
  geom_label(
    label = "Pre-2020",
    x = 2.5,
    y = 9.5,
    label.padding = unit(0.15, "lines"),
    label.size = 0.15,
    color = "black"
  ) +
  geom_label(
    label = "Post-2020",
    x = 19.5,
    y = 9.5,
    label.padding = unit(0.15, "lines"),
    label.size = 0.15,
    color = "black"
  ) +
  geom_vline(xintercept = 10.5, linetype = "dashed") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5)) 
  # annotate("rect", xmin = 2, xmax = 3, ymin = 0, ymax = 9,
  #          alpha = .25) +
  # annotate("rect", xmin = 6, xmax = 7, ymin = 0, ymax = 9,
  #          alpha = .25)
  
  
  
  
  
```
# Mean bed occupancy 

```{r}

clean_hospital_admissions_speciality %>% 
  mutate(pre_post_covid = case_when(pre_post_covid == "pre" ~ "Pre-2020",
                                    pre_post_covid == "post" ~ "Post-2020",
                                           TRUE ~ "")) %>% 
  filter(specialty_name %in% "Respiratory Medicine") %>% 
  group_by(quarter, specialty_name, pre_post_covid) %>% 
  summarise(mean(episodes),
            sd(episodes),
            sd(episodes)/sqrt(length(episodes)))

clean_hospital_admissions_speciality %>% 
  mutate(pre_post_covid = case_when(pre_post_covid == "pre" ~ "Pre-2020",
                                    pre_post_covid == "post" ~ "Post-2020",
                                           TRUE ~ "")) %>% 
  filter(specialty_name %in% "Respiratory Medicine") %>% 
  group_by(quarter, specialty_name, pre_post_covid) %>% 
  ggplot(aes(x = quarter, y = episodes, colour = specialty_name)) +
  stat_summary(fun.data = "mean_se",
               geom = "errorbar",
               width = 0.5) +
  stat_summary(fun = "mean", geom = "point", size = 4, shape = 17) +
  stat_summary(fun = "mean",
               geom = "line",
               group = 1) +
  facet_wrap(~factor(pre_post_covid, level = c("Pre-2020", "Post-2020"))) +
  labs(
    title = "Mean Quarterly Hospital Admissions for Specialities",
    x = "Quarter",
    y = "Hospital Admissions",
    col = "Speciality Name") 
```


```{r}
admission_demographics_all <- read_csv(here("app/clean_data/admission_demographics_all.csv"))
library(infer)
```
```{r}
admission_demographics_all %>% 
  group_by(sex) %>% 
  ggplot() +
  aes(x = factor(sex, ordered = TRUE, levels = c("Male", "Female")), y = episodes) +
  geom_violin(fill = "grey", color = "black", trim = FALSE) +
  stat_summary(fun.data = "mean_se", 
                 geom ="pointrange", width= 0.1, size = 0.5, colour = "black", linewidth = 1) +
  theme_bw() +
  ylim(0, 45000) +
  geom_label(label = "p = 0.62",
     x = 1.5,
     y = 45000,
     label.padding = unit(0.15, "lines"),
     label.size = 0.15,
     color = "black") +
   geom_segment(aes(x = 1, y = 42500, xend = 2, yend = 42500), color = "black", linewidth = 1) +
   labs(x = "Gender",
        y = "Mean Hospital Admissions")

```



```{r}
hosp_adm_q_split %>% 
  mutate(season = ifelse(quarter %in% c(2,3), "Spring/Summer", "Autumn/Winter")) %>% 
  filter(nhs_health_board != "All of Scotland") %>% 
  group_by(season) %>% 
  # summarise(total_hospital_admissions = sum(episodes),
  #            mean_hospital_admissions = mean(episodes),
  #            sd = sd(episodes)) %>% 
  ggplot() +
  aes(x = factor(season, ordered = TRUE, levels = c("Spring/Summer", "Autumn/Winter")), y = episodes) +
  geom_violin(fill = "grey", color = "black", trim = FALSE) +
  stat_summary(fun.data = "mean_se", 
                 geom ="pointrange", width= 0.1, size = 0.5, colour = "black", linewidth = 1) +
  theme_bw() +
  
  geom_label(label = "p = 0.976",
     x = 1.5,
     y = 134000,
     label.padding = unit(0.15, "lines"),
     label.size = 0.15,
     color = "black") +
   geom_segment(aes(x = 1, y = 130000, xend = 2, yend = 130000), color = "black", linewidth = 1) +
   labs(x = "Season",
        y = "Average Number of Hospital Admissions")
```

```{r}
pre_post_2020_avg_occupancy %>% 
  mutate(year = if_else(year == "post 2020", "2020 - 2022", "2017 - 2019")) %>% 
  filter(nhs_health_board %in% "Lothian") %>% 
  mutate(year = factor(year, levels = c("2017 - 2019", "2020 - 2022"))) %>% 
  ggplot(aes(x = factor(quarter, 
                        level = c("Q1", "Q2", "Q3", "Q4")), 
             y = percentage_occupancy, 
             group = nhs_health_board, 
             colour = nhs_health_board)) + 
  geom_point() +
  geom_line()+
  facet_wrap(~year) +
  labs(
    x = "Quarter", 
    y = "Percentage of Occupied Beds",
    title = "Mean Hospital Bed Occupancy per Location and Quarter",
    colour = "NHS Health Board"
  )
```

